### ISSUE TITLE
Support multiple workspaces

### ISSUE THREAD

**Issue by carsakiller** [carsakiller/vscode-lua#2]
Add support for users to enable/disable addons per-workspace.

On enable/disable:
```ts
const folder = await vscode.window.showWorkspaceFolderPick({
   ignoreFocusOut: true
});
```

# Tasks
- [x] Addon `enabled` field needs to be array of folders it is enabled in
- [x] Set `workspace.checkThirdParty` to `false` in chosen workspace
- [x] Will need to send number of open folders to [WebVue](https://github.com/carsakiller/vscode-lua-webvue)
